sudo: false
dist: trusty
language: c
compiler:
  - gcc
cache:
  directories:
    - $HOME/.cache
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
    - g++-mingw-w64-i686
    - re2c
env:
# - BASE=R3.14.12.6 STATIC=shared                     SEQ=2.2.4 ASYN=R4-31
  - BASE=R3.15.5    STATIC=share                      SEQ=      ASYN=R4-31
# - BASE=R3.15.5    STATIC=static                     SEQ=      ASYN=R4-31
#   - BASE=R3.15.5  STATIC=shared RTEMS=4.10          SEQ=2.2.4 ASYN=R4-31
  - BASE=R3.16.1    STATIC=shared                     SEQ=      ASYN=R4-31
#  - BASE=R3.16.1    STATIC=shared CMPLR=clang WINE=32 SEQ=      ASYN=R4-31
# - BASE=3.16       STATIC=static WINE=32             SEQ=2.2.4 ASYN=R4-31
  - BASE=R7.0.1-rc1 STATIC=shared                     SEQ=      ASYN=R4-31
    

install: ./.ci/travis-prepare.sh
script: make -C axisCore
