# Otherwise use Makefile

# Must check if some updated axisRecord.dbd.pod

AXISAUTOGENERATED = documentation/axisRecord.html \
                    axisApp/AxisSrc/axisRecord.dbd \
                    include/axisRecord.h


build: include/axisRecord.h

clean: rmaxisRecordDbd

rmaxisRecordDbd:
	rm -f $(AXISAUTOGENERATED)


$(AXISAUTOGENERATED): \
             axisApp/AxisSrc/axisRecord.dbd.pod \
             axisApp/tools/gen_axisRecord_html.sh
	rm -f $(AXISAUTOGENERATED)
	./axisApp/tools/gen_axisRecord_html.sh

#Use either the Makefile for EPICS, or the one for
# ESS EPICS ENVIRONMENT

ifdef EPICS_ENV_PATH
ifeq ($(EPICS_MODULES_PATH),/opt/epics/modules)
ifeq ($(EPICS_BASES_PATH),/opt/epics/bases)
include Makefile.EEE
else
include Makefile.epics
endif
else
include Makefile.epics
endif
else
include Makefile.epics
endif
