# Must check if some one updated axisRecord.dbd.pod

AXISAUTOGENERATED = axisCore/documentation/axisRecord.html \
                    axisCore/AxisSrc/axisRecord.dbd


install: $(AXISAUTOGENERATED)

build: $(AXISAUTOGENERATED)

clean: rmaxisRecordDbd

rmaxisRecordDbd:
	rm -f $(AXISAUTOGENERATED)


$(AXISAUTOGENERATED): \
             axisCore/AxisSrc/axisRecord.dbd.pod \
             axisCore/tools/gen_axisRecord_html.sh
	./axisCore/tools/gen_axisRecord_html.sh

#Use either the Makefile for EPICS, or the one for
# ESS EPICS ENVIRONMENT

ifdef EPICS_ENV_PATH
ifeq ($(EPICS_MODULES_PATH),/opt/epics/modules)
ifeq ($(EPICS_BASES_PATH),/opt/epics/bases)
include Makefile.EEE
else
include Makefile.epics
endif
else
include Makefile.epics
endif
else
include Makefile.epics
endif
